name: test

on:
  pull_request:
  push:
    branches:
      - main
      - staging
    tags:
      - '**'

jobs:
  everything:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Configure swap
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 4
      - run: nix build
      - run: nix develop -c sh -c 'make -f maint/Makefile -j2 outputs'
      - name: Compare some of the files
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir _nix _develop
          cp -- result/.version result/*.fb2 result/*.txt _nix/
          cp -- .version *.fb2 *.txt _develop/
          diff -qr _nix/ _develop/
      - run: nix develop -c sh -c 'make -f maint/Makefile -j1 all check'
      - run: nix flake check
      - uses: actions/upload-artifact@v4
        with:
          name: in-maxines-way
          if-no-files-found: error
          path: |
            in-maxines-way.en-ru.pdf
            in-maxines-way.en.pdf
            in-maxines-way.ru.pdf
            in-maxines-way.en.epub
            in-maxines-way.ru.epub
            in-maxines-way.en.fb2
            in-maxines-way.ru.fb2
            in-maxines-way.en.80column.txt
            in-maxines-way.ru.80column.txt
            in-maxines-way.en.freeflow.txt
            in-maxines-way.ru.freeflow.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          fail_on_unmatched_files: true
          files: |
            result/in-maxines-way.en-ru.pdf
            result/in-maxines-way.en.pdf
            result/in-maxines-way.ru.pdf
            result/in-maxines-way.en.epub
            result/in-maxines-way.ru.epub
            result/in-maxines-way.en.fb2
            result/in-maxines-way.ru.fb2
            result/in-maxines-way.en.80column.txt
            result/in-maxines-way.ru.80column.txt
            result/in-maxines-way.en.freeflow.txt
            result/in-maxines-way.ru.freeflow.txt
          token: ${{ secrets.RELEASE_TOKEN }}
